name: Deploy Azure Functions

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
 AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 

jobs:
  deploy:
    name: Deploy to Azure Functions
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Install dependencies
      #   run: npm install

      - name: 'Resolve Project Dependencies Using Npm'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          popd

      # - name: Archive production artifacts
      #   run: zip -r functionapp.zip . -x '*.git*'

      # - name: Archive production artifacts
      #   run: |
      #     powershell Compress-Archive -Path * -DestinationPath functionapp.zip -Force

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
          # package: functionapp.zip
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
